<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE geografia-mundial[
  <!ELEMENT geografia-mundial (pais)>
  <!ELEMENT pais (nombre, continente, capital)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT continente (#PCDATA)>
  <!ELEMENT capital (#PCDATA)>
]>

<geografia-mundial>
    <pais>
        <nombre>Espa√±a</nombre>
        <continente>Europa</continente>
        <capital>Madrid</capital>
    </pais>
</geografia-mundial>